<h1>
Recheck Now , before starting recheck whether every thing really cleaned ? . 
I DO NOT NEED . SO ,
REMOVE MULTI COMPANY SYSTEM ENTIRELY FROM MY DATABASE , REMOVE BARCODE SKU (AVAILABLE AT ITEM_ALIAS ) ENTIRELY FROM MY DATABASE , REMOVE AUDIT ( LIKE CREATED TIME, UPDATED TIME) RECORDS ENTIRELY FROM MY DATABASE . PROJECT .

!</h1>
