accounts	code	code	0	1	BTREE
accounts	idx_accounts_active	is_active	1	1	BTREE
accounts	idx_code	code	1	1	BTREE
accounts	idx_parent	parent_code	1	1	BTREE
accounts	idx_type	account_type	1	1	BTREE
accounts	PRIMARY	id	0	1	BTREE
app_settings	PRIMARY	setting_key	0	1	BTREE
bank_reconciliation	idx_account_date	bank_account_code	1	1	BTREE
bank_reconciliation	idx_account_date	statement_date	1	2	BTREE
bank_reconciliation	PRIMARY	id	0	1	BTREE
bank_reconciliation_items	idx_journal_line	journal_line_id	1	1	BTREE
bank_reconciliation_items	idx_reconciliation	reconciliation_id	1	1	BTREE
bank_reconciliation_items	PRIMARY	id	0	1	BTREE
bank_statements	idx_account_date	account_code	1	1	BTREE
bank_statements	idx_account_date	statement_date	1	2	BTREE
bank_statements	PRIMARY	id	0	1	BTREE
bank_statements	unique_statement	account_code	0	1	BTREE
bank_statements	unique_statement	statement_date	0	2	BTREE
bank_statement_lines	idx_journal	journal_entry_id	1	1	BTREE
bank_statement_lines	idx_reconciled	is_reconciled	1	1	BTREE
bank_statement_lines	idx_stmt_date	statement_id	1	1	BTREE
bank_statement_lines	idx_stmt_date	transaction_date	1	2	BTREE
bank_statement_lines	PRIMARY	id	0	1	BTREE
financial_periods	idx_active	is_active	1	1	BTREE
financial_periods	idx_dates	start_date	1	1	BTREE
financial_periods	idx_dates	end_date	1	2	BTREE
financial_periods	PRIMARY	id	0	1	BTREE
financial_periods	unique_period	start_date	0	1	BTREE
financial_periods	unique_period	end_date	0	2	BTREE
gst_hsn_rates	PRIMARY	hsn	0	1	BTREE
gst_rates	idx_gst_rates_total	total_rate	1	1	BTREE
gst_rates	PRIMARY	id	0	1	BTREE
gst_rate_rules	idx_gst_rules_effective	effective_from	1	1	BTREE
gst_rate_rules	idx_gst_rules_effective	effective_to	1	2	BTREE
gst_rate_rules	idx_gst_rules_hsn	hsn_chapter	1	1	BTREE
gst_rate_rules	idx_rules_eff	effective_from	1	1	BTREE
gst_rate_rules	idx_rules_eff	effective_to	1	2	BTREE
gst_rate_rules	idx_rules_range	hsn_chapter	1	1	BTREE
gst_rate_rules	idx_rules_range	hsn_start	1	2	BTREE
gst_rate_rules	idx_rules_range	hsn_end	1	3	BTREE
gst_rate_rules	PRIMARY	id	0	1	BTREE
inventory_movements	idx_item_date	item_id	1	1	BTREE
inventory_movements	idx_item_date	movement_date	1	2	BTREE
inventory_movements	idx_source	source_type	1	1	BTREE
inventory_movements	idx_source	source_id	1	2	BTREE
inventory_movements	PRIMARY	id	0	1	BTREE
inventory_valuations	idx_item_date	item_id	1	1	BTREE
inventory_valuations	idx_item_date	valuation_date	1	2	BTREE
inventory_valuations	PRIMARY	id	0	1	BTREE
inventory_valuations	unique_item_date	item_id	0	1	BTREE
inventory_valuations	unique_item_date	valuation_date	0	2	BTREE
invoices	idx_invoice_date	invoice_date	1	1	BTREE
invoices	idx_invoice_no	invoice_no	1	1	BTREE
invoices	idx_invoice_party	party_id	1	1	BTREE
invoices	idx_invoice_status	status	1	1	BTREE
invoices	idx_invoice_type	inv_type	1	1	BTREE
invoices	idx_inv_date	invoice_date	1	1	BTREE
invoices	idx_inv_party	party_id	1	1	BTREE
invoices	idx_inv_type	inv_type	1	1	BTREE
invoices	PRIMARY	id	0	1	BTREE
invoice_items	description	description	1	1	FULLTEXT
invoice_items	description_2	description	1	1	FULLTEXT
invoice_items	idx_invoice_id	invoice_id	1	1	BTREE
invoice_items	idx_item_description	description	1	1	BTREE
invoice_items	idx_item_hsn	hsn	1	1	BTREE
invoice_items	idx_item_id	item_id	1	1	BTREE
invoice_items	idx_item_invoice	invoice_id	1	1	BTREE
invoice_items	idx_item_rate	rate	1	1	BTREE
invoice_items	PRIMARY	id	0	1	BTREE
invoice_series	PRIMARY	id	0	1	BTREE
inv_id_map	PRIMARY	old_id	0	1	BTREE
items	ft_item_name	canonical_name	1	1	FULLTEXT
items	idx_item_hsn_code	hsn	1	1	BTREE
items	idx_item_name	canonical_name	1	1	BTREE
items	PRIMARY	id	0	1	BTREE
journals	PRIMARY	id	0	1	BTREE
journal_entries	idx_company_date	entry_date	1	1	BTREE
journal_entries	idx_journal_source	source_type	1	1	BTREE
journal_entries	idx_journal_source	source_id	1	2	BTREE
journal_entries	PRIMARY	id	0	1	BTREE
journal_lines	journal_id	entry_id	1	1	BTREE
journal_lines	PRIMARY	id	0	1	BTREE
organization_config	PRIMARY	id	0	1	BTREE
parties	idx_party_gstin	gstin	1	1	BTREE
parties	idx_party_name	name	1	1	BTREE
parties	idx_party_state	state	1	1	BTREE
parties	idx_party_type	party_type	1	1	BTREE
parties	PRIMARY	id	0	1	BTREE
parties	uq_parties_gstin	gstin	0	1	BTREE
payments	idx_pay_party_date	party_id	1	1	BTREE
payments	idx_pay_party_date	pay_date	1	2	BTREE
payments	PRIMARY	id	0	1	BTREE
purchase_invoice_staging	idx_staging_invoice_date	invoice_date	1	1	BTREE
purchase_invoice_staging	idx_staging_invoice_no	invoice_no	1	1	BTREE
purchase_invoice_staging	idx_staging_item_name	item_name	1	1	BTREE
purchase_invoice_staging	idx_staging_supplier	supplier_name	1	1	BTREE
purchase_invoice_staging	PRIMARY	id	0	1	BTREE
purchase_invoice_staging_reverse	idx_staging_invoice_date	invoice_date	1	1	BTREE
purchase_invoice_staging_reverse	idx_staging_invoice_no	invoice_no	1	1	BTREE
purchase_invoice_staging_reverse	idx_staging_item_name	item_name	1	1	BTREE
purchase_invoice_staging_reverse	idx_staging_supplier	supplier_name	1	1	BTREE
purchase_invoice_staging_reverse	PRIMARY	id	0	1	BTREE
staging_purchase_invoice	PRIMARY	id	0	1	BTREE
txn_ref_log	PRIMARY	id	0	1	BTREE
txn_ref_log	uq_txn_ref	ref_no	0	1	BTREE
txn_ref_log	uq_txn_ref	txn_date	0	2	BTREE
txn_ref_log	uq_txn_ref	amount	0	3	BTREE
txn_ref_log	uq_txn_ref	source	0	4	BTREE
uqc	code	code	0	1	BTREE
uqc	PRIMARY	id	0	1	BTREE
users	PRIMARY	id	0	1	BTREE
users	username	username	0	1	BTREE
