accounts	id
app_settings	setting_key
bank_reconciliation	id
bank_reconciliation_items	id
bank_statements	id
bank_statement_lines	id
financial_periods	id
gst_hsn_rates	hsn
gst_rates	id
gst_rate_rules	id
inventory_movements	id
inventory_valuations	id
invoices	id
invoice_items	id
invoice_series	id
inv_id_map	old_id
items	id
journals	id
journal_entries	id
journal_lines	id
organization_config	id
parties	id
payments	id
purchase_invoice_staging	id
purchase_invoice_staging_reverse	id
staging_purchase_invoice	id
txn_ref_log	id
uqc	id
users	id
